#!/bin/sh
set -eu

BINARY_PATH="$1"
USER_HOME="$2"
RUN_AS_USER="$3"
EXTRA_LD_LIBRARY_PATH="$4"
shift 4

RUN_AS_UID="$(id -u "$RUN_AS_USER")"
XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$RUN_AS_UID}"
LOG_FILE="${YAWC_TTY_LOG:-}"

if [ -n "$LOG_FILE" ]; then
  exec >> "$LOG_FILE" 2>&1
fi

ensure_portal_config() {
  if [ "${YAWC_SKIP_PORTAL_CONFIG:-0}" = "1" ]; then
    return 0
  fi

  config_home="${XDG_CONFIG_HOME:-$USER_HOME/.config}"
  portal_dir="$config_home/xdg-desktop-portal"
  if ! mkdir -p "$portal_dir" 2>/dev/null; then
    echo "warning: failed to create portal config directory: $portal_dir" >&2
    return 0
  fi

  for desktop in etyde yawc; do
    portal_file="$portal_dir/${desktop}-portals.conf"
    if [ -e "$portal_file" ]; then
      continue
    fi

    cat > "$portal_file" <<'EOF'
# Generated by YAWC. Edit this file to override portal backend selection.
[preferred]
default=kde;gtk;
org.freedesktop.impl.portal.Settings=kde;gtk;
org.freedesktop.impl.portal.FileChooser=kde;gtk;
org.freedesktop.impl.portal.AppChooser=gtk;kde;
org.freedesktop.impl.portal.ScreenCast=kde;none;
org.freedesktop.impl.portal.RemoteDesktop=kde;none;
org.freedesktop.impl.portal.Screenshot=kde;none;
org.freedesktop.impl.portal.Secret=kwallet;gnome-keyring;none;
EOF
    echo "Created YAWC portal config: $portal_file"
  done
}

ensure_portal_config

exec env \
  HOME="$USER_HOME" \
  USER="$RUN_AS_USER" \
  LOGNAME="$RUN_AS_USER" \
  XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
  XDG_SESSION_TYPE="wayland" \
  XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-etyDE:YAWC}" \
  XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-yawc}" \
  DESKTOP_SESSION="${DESKTOP_SESSION:-yawc}" \
  GDK_BACKEND="wayland" \
  QT_QPA_PLATFORM="wayland" \
  SDL_VIDEODRIVER="wayland" \
  CLUTTER_BACKEND="wayland" \
  MOZ_ENABLE_WAYLAND="1" \
  LIBSEAT_BACKEND="${YAWC_LIBSEAT_BACKEND:-logind}" \
  SMITHAY_USE_LEGACY="${YAWC_DRM_LEGACY:-1}" \
  YAWC_TTY_LOG="$LOG_FILE" \
  LD_LIBRARY_PATH="$EXTRA_LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
  dbus-run-session "$BINARY_PATH" --tty-udev "$@"
