#!/bin/sh
set -eu

YAWC_BINARY="${YAWC_BINARY:-/usr/local/bin/yawc}"
YAWC_REPO_DIR="${YAWC_REPO_DIR:-}"

if [ "${YAWC_SESSION_LOG_ACTIVE:-0}" != "1" ]; then
  state_home="${XDG_STATE_HOME:-${HOME:-/tmp}/.local/state}"
  log_dir="${YAWC_LOG_DIR:-$state_home/yawc}"
  mkdir -p "$log_dir"
  log_file="${YAWC_SESSION_LOG:-$log_dir/session.log}"
  : > "$log_file"
  export YAWC_SESSION_LOG_ACTIVE=1
  export YAWC_SESSION_LOG="$log_file"
  exec >> "$log_file" 2>&1
fi

echo "YAWC session log: ${YAWC_SESSION_LOG:-}"
echo "Starting YAWC session at $(date -Is 2>/dev/null || date)"

export PATH="${PATH:-/usr/local/bin:/usr/bin:/bin}"

add_library_dir() {
  if [ -d "$1" ]; then
    LD_LIBRARY_PATH="$1${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    export LD_LIBRARY_PATH
  fi
}

if [ -n "$YAWC_REPO_DIR" ]; then
  add_library_dir "$YAWC_REPO_DIR/.local-lib"
  add_library_dir "$YAWC_REPO_DIR/.sysroot/root/usr/lib/x86_64-linux-gnu"
fi

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ] \
  && [ "${YAWC_DBUS_WRAPPED:-0}" != "1" ] \
  && command -v dbus-run-session >/dev/null 2>&1
then
  export YAWC_DBUS_WRAPPED=1
  exec dbus-run-session "$0"
fi

find_startup_command() {
  if [ -n "${YAWC_STARTUP_COMMAND:-}" ]; then
    printf '%s\n' "$YAWC_STARTUP_COMMAND"
    return 0
  fi

  for candidate in \
    foot \
    weston-terminal \
    kgx \
    alacritty \
    wezterm \
    kitty
  do
    if command -v "$candidate" >/dev/null 2>&1; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  if command -v konsole >/dev/null 2>&1; then
    printf '%s\n' "konsole --separate"
    return 0
  fi

  for candidate in \
    gnome-terminal \
    xfce4-terminal \
    qterminal
  do
    if command -v "$candidate" >/dev/null 2>&1; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  return 1
}

if [ ! -x "$YAWC_BINARY" ]; then
  echo "error: YAWC binary is not executable: $YAWC_BINARY" >&2
  exit 1
fi

startup_command="$(find_startup_command || true)"
echo "YAWC startup command: ${startup_command:-<none>}"

export XDG_SESSION_TYPE="${XDG_SESSION_TYPE:-wayland}"
export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-etyDE:YAWC}"
export XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-yawc}"
export DESKTOP_SESSION="${DESKTOP_SESSION:-yawc}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME:-/tmp}/.local/share}"
case ":${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:" in
  *":$XDG_DATA_HOME:"*) ;;
  *) export XDG_DATA_DIRS="$XDG_DATA_HOME:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" ;;
esac

ensure_portal_config() {
  if [ "${YAWC_SKIP_PORTAL_CONFIG:-0}" = "1" ]; then
    return 0
  fi

  config_home="${XDG_CONFIG_HOME:-${HOME:-/tmp}/.config}"
  portal_dir="$config_home/xdg-desktop-portal"
  if ! mkdir -p "$portal_dir" 2>/dev/null; then
    echo "warning: failed to create portal config directory: $portal_dir" >&2
    return 0
  fi

  for desktop in YAWC etyDE etyde yawc; do
    portal_file="$portal_dir/${desktop}-portals.conf"
    if [ -e "$portal_file" ] && ! grep -q "Generated by YAWC" "$portal_file" 2>/dev/null; then
      continue
    fi

    cat > "$portal_file" <<'EOF'
# Generated by YAWC. Edit this file to override portal backend selection.
#
# YAWC does not depend on KDE or GNOME portal implementations. Until YAWC
# grows native implementations for more portal APIs, unsupported interfaces are
# left disabled instead of silently routing through another desktop.
[preferred]
default=none;
org.freedesktop.impl.portal.Settings=none;
org.freedesktop.impl.portal.FileChooser=none;
org.freedesktop.impl.portal.AppChooser=none;
org.freedesktop.impl.portal.ScreenCast=yawc;none;
org.freedesktop.impl.portal.RemoteDesktop=none;
org.freedesktop.impl.portal.Screenshot=yawc;none;
org.freedesktop.impl.portal.Secret=none;
EOF
    echo "Created YAWC portal config: $portal_file"
  done
}

ensure_portal_descriptors() {
  if [ "${YAWC_SKIP_PORTAL_CONFIG:-0}" = "1" ]; then
    return 0
  fi

  data_home="$XDG_DATA_HOME"
  portal_dir="$data_home/xdg-desktop-portal/portals"
  if ! mkdir -p "$portal_dir" 2>/dev/null; then
    echo "warning: failed to create portal descriptor directory: $portal_dir" >&2
    return 0
  fi

  for system_portal in /usr/share/xdg-desktop-portal/portals/*.portal; do
    [ -e "$system_portal" ] || continue
    portal_file="$portal_dir/$(basename "$system_portal")"
    if [ ! -e "$portal_file" ] || [ -L "$portal_file" ] || grep -q "Generated by YAWC" "$portal_file" 2>/dev/null; then
      ln -sfn "$system_portal" "$portal_file"
    fi
  done

  portal_file="$portal_dir/yawc.portal"
  if [ -e "$portal_file" ] && ! grep -q "Generated by YAWC" "$portal_file" 2>/dev/null; then
    return 0
  fi

  cat > "$portal_file" <<'EOF'
# Generated by YAWC. Allows xdg-desktop-portal-wlr to serve YAWC sessions.
[portal]
DBusName=org.freedesktop.impl.portal.desktop.wlr
Interfaces=org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.ScreenCast;
UseIn=YAWC;etyDE;yawc;
EOF
  export XDG_DESKTOP_PORTAL_DIR="$portal_dir"
  echo "Created YAWC portal descriptor: $portal_file"
}

ensure_wlr_config() {
  if [ "${YAWC_SKIP_PORTAL_CONFIG:-0}" = "1" ]; then
    return 0
  fi

  config_home="${XDG_CONFIG_HOME:-${HOME:-/tmp}/.config}"
  config_dir="$config_home/xdg-desktop-portal-wlr"
  if ! mkdir -p "$config_dir" 2>/dev/null; then
    echo "warning: failed to create xdg-desktop-portal-wlr config directory: $config_dir" >&2
    return 0
  fi

  for config_name in YAWC etyDE yawc config; do
    config_file="$config_dir/$config_name"
    if [ -e "$config_file" ] && ! grep -q "Generated by YAWC" "$config_file" 2>/dev/null; then
      continue
    fi

    cat > "$config_file" <<'EOF'
# Generated by YAWC. Avoid chooser overlays that require layer-shell.
[screencast]
chooser_type=none
max_fps=60
EOF
    echo "Created YAWC xdg-desktop-portal-wlr config: $config_file"
  done
}

reset_stale_portal_services() {
  if [ "${YAWC_SKIP_PORTAL_RESTART:-0}" = "1" ]; then
    return 0
  fi

  if ! command -v systemctl >/dev/null 2>&1; then
    return 0
  fi

  systemctl --user stop \
    xdg-desktop-portal.service \
    xdg-desktop-portal-wlr.service >/dev/null 2>&1 || true
  systemctl --user reset-failed \
    xdg-desktop-portal.service \
    xdg-desktop-portal-wlr.service >/dev/null 2>&1 || true
}

ensure_portal_config
ensure_portal_descriptors
ensure_wlr_config
reset_stale_portal_services

if [ ! -e /usr/share/xdg-desktop-portal/portals/wlr.portal ]; then
  echo "warning: xdg-desktop-portal-wlr is not installed; OBS screen capture will not be available" >&2
fi

avoid_software_gl_overrides() {
  case "${LIBGL_ALWAYS_SOFTWARE:-}" in
    1|true|TRUE|yes|YES|on|ON)
      echo "warning: unsetting LIBGL_ALWAYS_SOFTWARE so Wayland/EGL clients can use hardware GL" >&2
      unset LIBGL_ALWAYS_SOFTWARE
      ;;
  esac

  case "${MESA_LOADER_DRIVER_OVERRIDE:-}" in
    llvmpipe|softpipe|swrast)
      echo "warning: unsetting MESA_LOADER_DRIVER_OVERRIDE=$MESA_LOADER_DRIVER_OVERRIDE" >&2
      unset MESA_LOADER_DRIVER_OVERRIDE
      ;;
  esac
}

configure_gpu_vendor_overrides() {
  gpu_vendor="${YAWC_GPU_VENDOR:-${YAWC_DEFAULT_GPU_VENDOR:-auto}}"
  case "$gpu_vendor" in
    auto|"")
      ;;
    nvidia)
      if [ -e /usr/share/glvnd/egl_vendor.d/10_nvidia.json ]; then
        export __EGL_VENDOR_LIBRARY_FILENAMES="${__EGL_VENDOR_LIBRARY_FILENAMES:-/usr/share/glvnd/egl_vendor.d/10_nvidia.json}"
        export __GLX_VENDOR_LIBRARY_NAME="${__GLX_VENDOR_LIBRARY_NAME:-nvidia}"
        export GBM_BACKEND="${GBM_BACKEND:-nvidia-drm}"
      else
        echo "warning: YAWC_GPU_VENDOR=nvidia was requested but the NVIDIA EGL vendor file is missing" >&2
      fi
      ;;
    mesa)
      if [ -e /usr/share/glvnd/egl_vendor.d/50_mesa.json ]; then
        export __EGL_VENDOR_LIBRARY_FILENAMES="${__EGL_VENDOR_LIBRARY_FILENAMES:-/usr/share/glvnd/egl_vendor.d/50_mesa.json}"
      fi
      ;;
    *)
      echo "warning: unknown YAWC_GPU_VENDOR=$gpu_vendor; expected auto, mesa, or nvidia" >&2
      ;;
  esac
}

avoid_software_gl_overrides
configure_gpu_vendor_overrides

export GDK_BACKEND="${GDK_BACKEND:-wayland}"
export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-wayland}"
export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-wayland}"
export CLUTTER_BACKEND="${CLUTTER_BACKEND:-wayland}"
export MOZ_ENABLE_WAYLAND="${MOZ_ENABLE_WAYLAND:-1}"
export EGL_PLATFORM="${EGL_PLATFORM:-wayland}"

export LIBSEAT_BACKEND="${YAWC_LIBSEAT_BACKEND:-logind}"
export SMITHAY_USE_LEGACY="${YAWC_DRM_LEGACY:-0}"
export RUST_LOG="${RUST_LOG:-info,yawc=info}"

if [ -n "$startup_command" ]; then
  exec "$YAWC_BINARY" --standalone --command "$startup_command"
fi

exec "$YAWC_BINARY" --standalone
